version: $(core_version)+{branch}.{build}
configuration: Release
image: Visual Studio 2017

install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1

build_script:
  - dotnet --version
  - dotnet pack -c Release

test_script:
  - dotnet test .\Raven.Migrations.Tests\Raven.Migrations.Tests.csproj -c Release -f netcoreapp2.1
  
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(core_version)
  assembly_file_version: $(core_version)
  assembly_informational_version: $(core_version)

environment:
  core_version: 2.1.0

nuget:
  disable_publish_on_pr: true

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: OSeRx3pJdGAl1kbmZ5gYqA/0bQVededJ9PVS6Di0kRlKAqh0DKb5+T1cyrf38Ni0
  on:
    appveyor_repo_tag: true
